[[abbreviations]]
key = "b"
value = "brew"
platform = "darwin"

[[abbreviations]]
key = "bi"
value = "brew install"
platform = "darwin"

[[abbreviations]]
key = "brci"
value = "brew install --cask"
platform = "darwin"

[[abbreviations]]
key = "brcu"
value = "brew uninstall --cask"
platform = "darwin"

[[abbreviations]]
key = "brcz"
value = "brew uninstall --cask --zap"
platform = "darwin"

[[abbreviations]]
key = "bz"
value = "brew uninstall --zap"
platform = "darwin"

[[abbreviations]]
key = "ci"
value = "brew install --cask"
platform = "darwin"

[[abbreviations]]
key = "cz"
value = "chezmoi"

[[abbreviations]]
key = "cdd"
value = "chezmoi cd ~"

[[abbreviations]]
key = "dp"
value = "chezmoi apply -v"

[[abbreviations]]
key = "ll"
value = "ls -l"

[[abbreviations]]
key = "la"
value = "ls -al"

[[abbreviations]]
key = "gg"
value = "lazygit"

[[abbreviations]]
key = "md"
value = "mkdir -p"

[[abbreviations]]
key = "e"
value = "nvim"
